In [3]:
# Installing the necessary packages:

install.packages("tidyverse")
library(tidyverse)
library(lubridate)

Installing package into ‘/srv/rlibs’
(as ‘lib’ is unspecified)

Registered S3 methods overwritten by 'tibble':
  method     from
  format.tbl pillar
  print.tbl  pillar

Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang

Registered S3 method overwritten by 'rvest':
  method            from
  read_xml.response xml2

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──

✔ ggplot2 3.1.1       ✔ purrr   0.3.2
✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
✔ tidyr   0.8.3       ✔ stringr 1.4.0
✔ readr   1.3.1       ✔ forcats 0.4.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Attaching package: ‘lubridate’


The following object is masked from ‘package:base’:

    date

In [28]:
# Creating two columns for given_time and current_time respectively:

given_time <- c("11:00:00", "07:10:12", "16:08:04")
current_datetime <- c(now())                        #now() functions gives the current time (in UTC time zone by default)

df <- data.frame(given_time, current_datetime)

Warning message in with_tz(Sys.time(), tzone):
“Unrecognized time zone ''”

In [29]:
# Previewing the dataframe:

head(df)

  given_time current_datetime
1 11:00:00   2021-06-25 08:42:18
2 07:10:12   2021-06-25 08:42:18
3 16:08:04   2021-06-25 08:42:18

In [30]:
# Seperating datetime column in date and time:

df <- df %>%
    separate(current_datetime, c("current_date", "current_time"), sep=" ")

In [31]:
head(df)

  given_time current_date current_time
1 11:00:00   2021-06-25   08:42:18
2 07:10:12   2021-06-25   08:42:18
3 16:08:04   2021-06-25   08:42:18

In [32]:
df <- mutate(df, given_time = as.character(given_time))

In [33]:
head(df)

  given_time current_date current_time
1 11:00:00   2021-06-25   08:42:18
2 07:10:12   2021-06-25   08:42:18
3 16:08:04   2021-06-25   08:42:18

In [34]:
df <- df %>% mutate(given_time = hms::as.hms(given_time), current_time= hms::as.hms(current_time))

In [35]:
head(df)

  given_time current_date current_time
1 11:00:00   2021-06-25   08:42:18
2 07:10:12   2021-06-25   08:42:18
3 16:08:04   2021-06-25   08:42:18

In [36]:
df$time_diff <- difftime(df$given_time,df$current_time)

In [37]:
head(df)

  given_time current_date current_time time_diff
1 11:00:00   2021-06-25   08:42:18      2.295000 hours
2 07:10:12   2021-06-25   08:42:18     -1.535000 hours
3 16:08:04   2021-06-25   08:42:18      7.429444 hours

In [ ]:
# The above column of time_diff represents the time difference between the two columns.